//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFTPManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SFTPManager.Resources.Resources-en", typeof(Resources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to execute command.
        /// </summary>
        public static string CommandErrorMessage {
            get {
                return ResourceManager.GetString("CommandErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CommandErrorTitle.
        /// </summary>
        public static string CommandErrorTitle {
            get {
                return ResourceManager.GetString("CommandErrorTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter a command..
        /// </summary>
        public static string CommandPrompt {
            get {
                return ResourceManager.GetString("CommandPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string CommandTitle {
            get {
                return ResourceManager.GetString("CommandTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SFTP connection successful..
        /// </summary>
        public static string ConnectionSuccessful {
            get {
                return ResourceManager.GetString("ConnectionSuccessful", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        public static string ConnectionUnsuccessful {
            get {
                return ResourceManager.GetString("ConnectionUnsuccessful", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Successfully disconnected from the server..
        /// </summary>
        public static string DisconnectedSuccessfully {
            get {
                return ResourceManager.GetString("DisconnectedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Downloaded Successfully..
        /// </summary>
        public static string DownloadSuccess {
            get {
                return ResourceManager.GetString("DownloadSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select both local and remote paths..
        /// </summary>
        public static string ErrorSelectPaths {
            get {
                return ResourceManager.GetString("ErrorSelectPaths", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File Download Failed.
        /// </summary>
        public static string FileDownloadFailed {
            get {
                return ResourceManager.GetString("FileDownloadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File already exists. Attempting to overwrite....
        /// </summary>
        public static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File system loaded successfully..
        /// </summary>
        public static string FileSystemLoaded {
            get {
                return ResourceManager.GetString("FileSystemLoaded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File Upload Failed.
        /// </summary>
        public static string FileUploadFailed {
            get {
                return ResourceManager.GetString("FileUploadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uploaded Successfully..
        /// </summary>
        public static string UploadSuccess {
            get {
                return ResourceManager.GetString("UploadSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The hostname or IP address you have entered appears to be invalid..
        /// </summary>
        public static string ValidationInvalidHostOrIp {
            get {
                return ResourceManager.GetString("ValidationInvalidHostOrIp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please fill in both server and username fields..
        /// </summary>
        public static string ValidationServerUsernameEmpty {
            get {
                return ResourceManager.GetString("ValidationServerUsernameEmpty", resourceCulture);
            }
        }
    }
}
